#!/usr/bin/env bash
set -euo pipefail

# One-command Pi 5 kiosk installer for CribGuard.
# Run from the repo:
#   bash deploy/pi/install-kiosk.sh
#
# Optional overrides:
#   CRIBGUARD_USER=<user>
#   CRIBGUARD_REPO_DIR=/home/<user>/CribGuard-Display
#   CRIBGUARD_BUILD_DIR=/home/<user>/CribGuard-Display/build-pi
#   SDL_VIDEO_KMSDRM_ROTATION=90

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR_DEFAULT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
REPO_DIR="${CRIBGUARD_REPO_DIR:-${REPO_DIR_DEFAULT}}"
BUILD_DIR="${CRIBGUARD_BUILD_DIR:-${REPO_DIR}/build-pi}"
ROTATION="${SDL_VIDEO_KMSDRM_ROTATION:-${CRIBGUARD_ROTATION:-90}}"

if [[ -z "${CRIBGUARD_USER:-}" ]]; then
  if [[ -n "${SUDO_USER:-}" && "${SUDO_USER}" != "root" ]]; then
    CRIBGUARD_USER="${SUDO_USER}"
  else
    CRIBGUARD_USER="$(id -un)"
  fi
fi

if [[ "${CRIBGUARD_USER}" == "root" ]]; then
  echo "ERROR: target user resolved to root. Set CRIBGUARD_USER to a normal account." >&2
  exit 1
fi

CRIBGUARD_HOME="$(getent passwd "${CRIBGUARD_USER}" | cut -d: -f6 || true)"
if [[ -z "${CRIBGUARD_HOME}" ]]; then
  CRIBGUARD_HOME="/home/${CRIBGUARD_USER}"
fi

if [[ ! -d "${REPO_DIR}" ]]; then
  echo "ERROR: repo directory not found: ${REPO_DIR}" >&2
  exit 1
fi

SUDO=""
if [[ "$(id -u)" -ne 0 ]]; then
  SUDO="sudo"
fi

echo "[Pi5] Installing build/runtime packages..."
${SUDO} apt update
${SUDO} apt install -y \
  git cmake build-essential ninja-build pkg-config \
  libsdl2-dev libcurl4-openssl-dev \
  gstreamer1.0-tools gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
  gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-gl \
  libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
  libopencv-dev libuvc-dev libzmq3-dev

echo "[Pi5] Ensuring ${CRIBGUARD_USER} is in video,input groups..."
${SUDO} usermod -aG video,input "${CRIBGUARD_USER}" || true

echo "[Pi5] Building CribGuard..."
if (cd "${REPO_DIR}" && cmake --list-presets 2>/dev/null | grep -q "\"pi5-rel\""); then
  (
    cd "${REPO_DIR}"
    cmake --preset pi5-rel
    cmake --build --preset pi5-rel -j"$(nproc)"
  )
else
  cmake -S "${REPO_DIR}" -B "${BUILD_DIR}" -G Ninja -DCMAKE_BUILD_TYPE=Release
  cmake --build "${BUILD_DIR}" -j"$(nproc)"
fi

echo "[Pi5] Installing launcher and systemd unit..."
${SUDO} install -m 0755 "${SCRIPT_DIR}/cribguard-run.sh" /usr/local/bin/cribguard-run.sh
# This repo file is installed as a template service.
${SUDO} install -m 0644 "${SCRIPT_DIR}/cribguard.service" /etc/systemd/system/cribguard@.service

TMP_ENV="$(mktemp)"
cat > "${TMP_ENV}" <<EOF
# Generated by deploy/pi/install-kiosk.sh
CRIBGUARD_USER="${CRIBGUARD_USER}"
CRIBGUARD_HOME="${CRIBGUARD_HOME}"
CRIBGUARD_REPO_DIR="${REPO_DIR}"
CRIBGUARD_BUILD_DIR="${BUILD_DIR}"
SDL_VIDEODRIVER="kmsdrm"
SDL_AUDIODRIVER="alsa"
SDL_VIDEO_KMSDRM_ROTATION="${ROTATION}"
EOF
${SUDO} install -m 0644 "${TMP_ENV}" /etc/default/cribguard
rm -f "${TMP_ENV}"

echo "[Pi5] Enabling kiosk service..."
${SUDO} systemctl disable --now cribguard.service >/dev/null 2>&1 || true
${SUDO} systemctl daemon-reload
${SUDO} systemctl enable --now "cribguard@${CRIBGUARD_USER}.service"

echo
echo "[Pi5] Done."
echo "Service: cribguard@${CRIBGUARD_USER}.service"
echo "Logs:    journalctl -u cribguard@${CRIBGUARD_USER}.service -b -f"
echo "Reboot recommended if group membership was newly applied:"
echo "  sudo reboot"
